# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 as base
WORKDIR /usr/src/app
# run the app
COPY JSTodoist/.output .
ENTRYPOINT [ "bun", "server/index.mjs" ]