version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "7777:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5555:3000"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_LOCALHOST: postgres
