# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB mydatabase

# Optionally, you can expose the PostgreSQL port (default is 5432)
EXPOSE 7777:5432

# Optionally, you can add initialization SQL scripts (e.g., schema and data)
# Copy your SQL script to the /docker-entrypoint-initdb.d/ directory
COPY init.sql /docker-entrypoint-initdb.d/

# This script will be executed when the container starts
CMD ["postgres"]